from typing import Protocol

from app.types.context import CONTEXT_ROLE, ConversationContext


class IContextStorage(Protocol):
    async def enable_chat(self, chat_id: str, topic_id: str | None = None) -> None: ...

    async def disable_chat(self, chat_id: str, topic_id: str | None = None) -> None: ...

    async def is_chat_enabled(self, chat_id: str, topic_id: str | None = None) -> bool: ...

    async def set_summary(self, key: str, summary: str) -> None: ...

    async def get_summary(self, key: str) -> str | None: ...

    async def add_message(self, key: str, role: CONTEXT_ROLE, content: str) -> None: ...

    async def get_messages(
        self, key: str, with_tokens: bool = False
    ) -> ConversationContext | None: ...

    async def clean(self, key: str) -> None: ...

    async def get_context(self, key: str) -> ConversationContext | None: ...
